import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Providers from './providers'
import Link from 'next/link'
import ThemeSwitcher from './components/ThemeSwitcher'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Providers>
          <header className='py-6'>
            <nav className='container flex items-center justify-between' id='nav-bar'>
              <ul className='ul_navbar'>
                <li><Link href='/'>Home</Link></li>
                <li><Link href='/ml_page'>Titanic Prediction Demo</Link></li>
                <li><Link href='/ocr'>OCR CPF Demo</Link></li>
                <li><Link href='/sentiment_analysis'>Sentiment Analysis Demo</Link></li>
              </ul>
              
            </nav>
          </header>
          <main>{children}</main>
          <footer>
          <ThemeSwitcher />
          </footer>
        </Providers>
      </body>
    </html>
  )
}
